services:
  master:
    build: .
    command: master_node tcp://*:5555
    ports:
      - "5555:5555"
    networks:
      - serverlink-net

  worker:
    build: .
    command: worker_node tcp://master:5555
    depends_on:
      - master
    networks:
      - serverlink-net

networks:
  serverlink-net:
    driver: bridge
